src/Entity/PictoAnimaux.php
<?php

namespace App\Entity;

use App\Repository\PictoAnimauxRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=PictoAnimauxRepository::class)
 * @Vich\Uploadable()
 */
class PictoAnimaux
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("pictoAnimaux")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("pictoAnimaux")
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups("pictoAnimaux")
     */
    private $filename;

     /**
     * @var File
     * @Assert\Image(
     *     mimeTypes={"image/gif", "image/png"}
     * )
     * @Vich\UploadableField(mapping="pictogram_image", fileNameProperty="filename")
    */
    private $illustration;


    /**
     * @ORM\Column(type="datetime")
     */
    private $update_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $genre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $pluriel;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_sing;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_sing;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_sing;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_plur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_plur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_plur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $masculin_sing;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $masculin_plur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $feminin_sing;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $feminin_plur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_sing_futur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_sing_futur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_sing_futur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_plur_futur;


    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_plur_futur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_plur_futur;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_sing_passe;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_sing_passe;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_sing_passe;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $prem_pers_plur_passe;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $deux_pers_plur_passe;


    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $trois_pers_plur_passe;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="pictoAnimauxes")
     * @ORM\JoinColumn(nullable=true)
     * @Groups("pictoAnimaux")
     */
    private $pictograms;

   

    /**
     * @ORM\ManyToMany(targetEntity=Sentence::class, inversedBy="pictoAnimauxes")
     */
    private $sentences;

    /**
     * @ORM\ManyToOne(targetEntity=Therapist::class, inversedBy="pictoAnimauxes")
     */
    private $therapist;

     public function __construct()
    {
       
        //$this->categories = new ArrayCollection();
        $this->sentences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getGenre(): ?string
    {
        return $this->genre;
    }

    public function setGenre(?string $genre): self
    {
        $this->genre = $genre;

        return $this;
    }

    public function getPluriel(): ?string
    {
        return $this->pluriel;
    }

    public function setPluriel(?string $pluriel): self
    {
        $this->pluriel = $pluriel;

        return $this;
    }

    public function getPremPersSing(): ?string
    {
        return $this->prem_pers_sing;
    }

    public function setPremPersSing(?string $prem_pers_sing): self
    {
        $this->prem_pers_sing = $prem_pers_sing;

        return $this;
    }

    public function getDeuxPersSing(): ?string
    {
        return $this->deux_pers_sing;
    }

    public function setDeuxPersSing(?string $deux_pers_sing): self
    {
        $this->deux_pers_sing = $deux_pers_sing;

        return $this;
    }

    public function getTroisPersSing(): ?string
    {
        return $this->trois_pers_sing;
    }

    public function setTroisPersSing(?string $trois_pers_sing): self
    {
        $this->trois_pers_sing = $trois_pers_sing;

        return $this;
    }

    public function getPremPersPlur(): ?string
    {
        return $this->prem_pers_plur;
    }

    public function setPremPersPlur(?string $prem_pers_plur): self
    {
        $this->prem_pers_plur = $prem_pers_plur;

        return $this;
    }

    public function getDeuxPersPlur(): ?string
    {
        return $this->deux_pers_plur;
    }

    public function setDeuxPersPlur(?string $deux_pers_plur): self
    {
        $this->deux_pers_plur = $deux_pers_plur;

        return $this;
    }

    public function getTroisPersPlur(): ?string
    {
        return $this->trois_pers_plur;
    }

    public function setTroisPersPlur(?string $trois_pers_plur): self
    {
        $this->trois_pers_plur = $trois_pers_plur;

        return $this;
    }


    public function getMasculinSing(): ?string
    {
        return $this->masculin_sing;
    }

    public function setMasculinSing(?string $masculin_sing): self
    {
        $this->masculin_sing = $masculin_sing;

        return $this;
    }

    public function getMasculinPlur(): ?string
    {
        return $this->masculin_plur;
    }

    public function setMasculinPlur(?string $masculin_plur): self
    {
        $this->masculin_plur = $masculin_plur;

        return $this;
    }

    public function getFemininSing(): ?string
    {
        return $this->feminin_sing;
    }

    public function setFemininSing(?string $feminin_sing): self
    {
        $this->feminin_sing = $feminin_sing;

        return $this;
    }

    public function getFemininPlur(): ?string
    {
        return $this->feminin_plur;
    }

    public function setFemininPlur(?string $feminin_plur): self
    {
        $this->feminin_plur = $feminin_plur;

        return $this;
    }

    public function getPremPersSingFutur(): ?string
    {
        return $this->prem_pers_sing_futur;
    }

    public function setPremPersSingFutur(?string $prem_pers_sing_futur): self
    {
        $this->prem_pers_sing_futur = $prem_pers_sing_futur;

        return $this;
    }

    public function getDeuxPersSingFutur(): ?string
    {
        return $this->deux_pers_sing_futur;
    }

    public function setDeuxPersSingFutur(?string $deux_pers_sing_futur): self
    {
        $this->deux_pers_sing_futur = $deux_pers_sing_futur;

        return $this;
    }

    public function getTroisPersSingFutur(): ?string
    {
        return $this->trois_pers_sing_futur;
    }

    public function setTroisPersSingFutur(?string $trois_pers_sing_futur): self
    {
        $this->trois_pers_sing_futur = $trois_pers_sing_futur;

        return $this;
    }

    public function getPremPersPlurFutur(): ?string
    {
        return $this->prem_pers_plur_futur;
    }

    public function setPremPersPlurFutur(?string $prem_pers_plur_futur): self
    {
        $this->prem_pers_plur_futur = $prem_pers_plur_futur;

        return $this;
    }

src/Controller/PictoAnimauxController.php
<?php

namespace App\Controller;

use App\Entity\PictoAnimaux;
use App\Form\PictoAnimauxType;
use App\Repository\CategoryRepository;
use App\Repository\PictoAnimauxRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/picto/animaux")
 */
class PictoAnimauxController extends AbstractController
{
    /**
     * @var CategoryRepository
     */
    private $repository;
    /**
     * @var EntityManagerInterface
     */
    private $em;

    public function __construct(PictoAnimauxRepository $repository, EntityManagerInterface $em)
    {
        $this->repository = $repository;
        $this->em = $em;
    }
    /**
     * @Route("/", name="app_picto_animaux_index", methods={"GET"})
     */
    public function index(PictoAnimauxRepository $pictoAnimauxRepository ,CategoryRepository $category): Response
    {
        $category=$this->repository->findByName(['name' => 'Animaux']);
        return $this->render('picto_animaux/index.html.twig', [
            'picto_animauxes' => $pictoAnimauxRepository->findAll(),
            'category' => $category
        ]);
    }

    /**
     * @Route("/new", name="app_picto_animaux_new", methods={"GET", "POST"})
     */
    public function new(Request $request): Response
    {
        $pictogram = new PictoAnimaux();
        $form = $this->createForm(PictoAnimauxType::class, $pictogram);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

              $category = $form->get('pictograms')->getData();
            // $subcategory = $form->get('subcategory_id')->getData();
            // if ( $category  && $subcategory) {
            //     $this->addFlash('echec', 'Ne peut avoir qu\'une catégorie ou une sous-catégorie');
            //     return $this->redirectToRoute('app_picto_animaux_new');
             if (!$category ) {
                $this->addFlash('echec', 'Doit posséder une catégorie ');
                return $this->redirectToRoute('app_picto_adjectifs_new');
            } else {
                $pictogram = $form->getData();
                $this->em->persist($pictogram);
                $this->em->flush();
                $this->addFlash('success', 'Pictogramme créé avec succès');
                return $this->redirectToRoute('app_picto_picto');
            }
        }
          return $this->render('picto_animaux/new.html.twig', [
            'pictograms' => $pictogram,
            'form' => $form->createView(),
            
        ]);
        //     $pictoAnimauxRepository->add($pictoAnimaux);
        //     return $this->redirectToRoute('app_picto_animaux_index', [], Response::HTTP_SEE_OTHER);
        // }

        // return $this->render('picto_animaux/new.html.twig', [
        //     'picto_animaux' => $pictoAnimaux,
        //     'form' => $form->createView(),
        // ]);
    }

    /**
     * @Route("/{id}", name="app_picto_animaux_show", methods={"GET"})
     */
    public function show(PictoAnimaux $pictoAnimaux): Response
    {
        return $this->render('picto_animaux/show.html.twig', [
            'picto_animaux' => $pictoAnimaux,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_picto_animaux_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, PictoAnimaux $pictoAnimaux, PictoAnimauxRepository $pictoAnimauxRepository): Response
    {
        $form = $this->createForm(PictoAnimauxType::class, $pictoAnimaux);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $pictoAnimauxRepository->add($pictoAnimaux);
            return $this->redirectToRoute('app_picto_animaux_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('picto_animaux/edit.html.twig', [
            'picto_animaux' => $pictoAnimaux,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="app_picto_animaux_delete", methods={"POST"})
     */
    public function delete(Request $request, PictoAnimaux $pictoAnimaux, PictoAnimauxRepository $pictoAnimauxRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pictoAnimaux->getId(), $request->request->get('_token'))) {
            $pictoAnimauxRepository->remove($pictoAnimaux);
        }

        return $this->redirectToRoute('app_picto_animaux_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/picto_animaux/_delete_form.html.twig
<form method="post" action="{{ path('app_picto_animaux_delete', {'id': picto_animaux.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ picto_animaux.id) }}">
    <button class="btn">Delete</button>
</form>

templates/picto_animaux/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }} #}

templates/picto_animaux/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit PictoAnimaux{% endblock %}

{% block body %}
    <h1>Edit PictoAnimaux</h1>

    {{ include('picto_animaux/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_picto_animaux_index') }}">back to list</a>

    {{ include('picto_animaux/_delete_form.html.twig') }}
{% endblock %}

templates/picto_animaux/index.html.twig
{% extends 'baseTherapist.html.twig' %}

{% block title %}Création d'un Pictogramme Animaux| PictoPicto{% endblock %}

{% block content %}

    <span class="title">AictoAnimaux, Catégories et Sous-Catégories</span>
<div class="d-flex justify-content-between">
                  
         <!-- btn création catégories et picotgrammes -->
        <div class="pictoactions">
               <a href="{{ path('app_picto_animaux_new') }}" class="btn btn-dark btn-sm">PictoAnimaux</a>
            
        </div>
         {# <!-- btn pour retour à la page PictiPcto qui regroupe toutes les pictotgrammes -->
        <div class="PictoPicto">
         <a href="{{ path('app_picto_picto') }}" class="btn btn-dark btn-sm">retour liste PictoPicto</a>
         </div>     #}
</div>
<div class="container-fluid mt-3 p-4 background">
        <div class="row">
            <div class="col-12">
                {% for message in app.flashes('success') %}
                    <div class="alert alert-success">
                        {{ message }}
                    </div>
                {% endfor %}
                {% for message in app.flashes('alert') %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% endfor %}
</div>
</div>
</div>

 <div id="accordion">
        <div class="p-3 accordion-item d-flex">
                <img class="pictoList" src="{{ asset('images/categories/'~picto_animauxes[0].pictograms.filename) }}" alt=""> 
                <span class="my-auto ms-2 ">{{ picto_animauxes[0].pictograms.name }}</span> 
              
            </div>       


     <div class="picto">
     {% for picto_animaux in picto_animauxes %}
                   <div class="ms-md-3">
                     <img class="pictoList"src="{{ asset('images/pictograms/') }}{{ picto_animaux.filename }}" alt=""> 
                    <figcaption class="picText">{{ picto_animaux.name }} </figcaption>
                            
                    </div>
                   
                      {% endfor %}
    </div>
    </div>      
{% endblock %}
      

templates/picto_animaux/new.html.twig
{% extends 'baseTherapist.html.twig' %}

{% block title %}Création d'un Pictogramme | PictoPicto{% endblock %}

{# {% block body %} #}
{% block content %}
    <!-- titre de l'item choisi -->
    <span class="title">Ajout d'un Pictogramme Animaux</span>
    {% for message in app.flashes('echec') %}
      <div class="alert alert-danger">
        {{ message }}
      </div>
    {% endfor %}
    {% if not form.vars.valid %}
        <ul class="alert alert-danger">
            {# on affiche en premier les erreurs globales (cas classiques) #}
            {% for error in form.vars.errors %}
                <li>{{error.message}}</li>
            {% endfor %}
            {# ainsi que les erreurs concernant chaque champs #}
            {% for child in form.children %}
                {# si le champ à des erreur #}
                {% if child.vars.errors is defined %}
                    {% for error in child.vars.errors %}
                        <li> {{error.message}} </li> {# on ajoute le label du champ devant l'erreur pour plus de précisions. #}
                    {% endfor %}
                {% endif %}
            {% endfor %}
        </ul>
    {% endif %}
    <div class="container-fluid mt-3 px-4 background">
        <p class="pt-4">
            PictoPicto vous laisse l'opportunité de créer vos propres pictogrammes!<br/>
            Pour une meilleure expérience utilisateur, il est recommandé de remplir tous les champs qui se rapporteraient au mot à insérer.
        </p>
        <div class="py-1">
            {{ form_start(form) }}
            <div class="row my-2">
                <div class="col">
                    {{ form_label(form.name) }}{{ form_widget(form.name) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.illustration) }}{{ form_widget(form.illustration) }}
                </div>
            </div>
            <div class="row my-1">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.pictograms) }}{{ form_widget(form.pictograms) }}
                    <div class="form-text">Veuillez sélectionner soit une catégorie .</div>
                </div>
                <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.pluriel) }}{{ form_widget(form.pluriel) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.prem_pers_sing) }}{{ form_widget(form.prem_pers_sing) }}
                </div>
            </div>
            <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.deux_pers_sing) }}{{ form_widget(form.deux_pers_sing) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.trois_pers_sing) }}{{ form_widget(form.trois_pers_sing) }}
                </div>
            </div>
            <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.prem_pers_plur) }}{{ form_widget(form.prem_pers_plur) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.deux_pers_plur) }}{{ form_widget(form.deux_pers_plur) }}
                </div>
            </div>
            <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.trois_pers_plur) }}{{ form_widget(form.trois_pers_plur) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.masculin_sing) }}{{ form_widget(form.masculin_sing) }}
                </div>
            </div>
            <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.masculin_plur) }}{{ form_widget(form.masculin_plur) }}
                </div>
                <div class="col" id="some-custom-id">
                    {{ form_label(form.feminin_sing) }}{{ form_widget(form.feminin_sing) }}
                </div>
            </div>
            <div class="row my-2">
                <div class="col" id="some-custom-id">
                    {{ form_label(form.feminin_plur) }}{{ form_widget(form.feminin_plur) }}
                </div>
            </div>
            {{ form_label(form.genre) }}{{ form_widget(form.genre) }}
            <div class="text-center my-4">
                {{ form_row(form.submit) }}
            </div>
            {{ form_end(form) }}
      
{% endblock %}

templates/picto_animaux/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}PictoAnimaux{% endblock %}

{% block body %}
    <h1>PictoAnimaux</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ picto_animaux.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ picto_animaux.name }}</td>
            </tr>
            <tr>
                <th>Filename</th>
                <td>{{ picto_animaux.filename }}</td>
            </tr>
            <tr>
                <th>Update_at</th>
                <td>{{ picto_animaux.updateAt ? picto_animaux.updateAt|date('Y-m-d ') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_picto_animaux_index') }}">Retour à la liste des PictoAnimaux</a>

    <a href="{{ path('app_picto_animaux_new') }}">Create new PictoAnimaux</a>

    {# {{ include('picto_animaux/_delete_form.html.twig') }} #}
{% endblock %}